# Section A: Data Structures & Control Structures

In [1]:
# Create list
lst = [10, 20, 30, 40, 50]
print("Original List:", lst)

# append
lst.append(60)
print("After append:", lst)

# extend
lst.extend([70, 80])
print("After extend:", lst)

# insert
lst.insert(2, 25)
print("After insert:", lst)

# remove
lst.remove(40)
print("After remove:", lst)

# pop
lst.pop()
print("After pop:", lst)

# index
print("Index of 30:", lst.index(30))

# count
print("Count of 20:", lst.count(20))

# sort
lst.sort()
print("After sort:", lst)

# reverse
lst.reverse()
print("After reverse:", lst)

# clear
lst.clear()
print("After clear:", lst)

Original List: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
After sort: [10, 20, 25, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 25, 20, 10]
After clear: []


In [2]:
students = ("Alice", "Bob", "Charlie")

# Trying to change second element
students[1] = "David"

TypeError: 'tuple' object does not support item assignment

In [3]:
s = {1, 2, 2, 3, 4, 4, 5}
print("Set:", s)

Set: {1, 2, 3, 4, 5}


In [5]:
person = {
    'name': 'John',
    'age': 25,
    'city': 'Mumbai'
}

# Update age
person['age'] = 26

# Add email
person['email'] = 'john@example.com'

print("Updated Dictionary:", person)

Updated Dictionary: {'name': 'John', 'age': 26, 'city': 'Mumbai', 'email': 'john@example.com'}


In [6]:
age = 20

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [7]:
marks = 82

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Fail")

Grade: B


In [8]:
num = 4

if num > 0:
    print("Positive number")
    if num % 2 == 0:
        print("Even number")
    else:
        print("Odd number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")

Positive number
Even number


# Section B: Numpy

In [10]:
import numpy as np

In [11]:
# Scalar
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# 2D array
arr2 = np.arange(10, 70, 10).reshape(2, 3)
print("2D Array:\n", arr2)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [12]:
rand_arr = np.random.randint(0, 101, (4, 4))
print("Random Array:\n", rand_arr)

Random Array:
 [[81 65 97 59]
 [41 81 76 66]
 [ 8  3 31 12]
 [61 41 87 32]]


In [13]:
import pandas as pd

arr = np.random.randint(1, 10, (3, 3))
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

print("DataFrame:\n", df)

DataFrame:
    A  B  C
0  9  4  2
1  5  5  2
2  5  7  7


# Section C: Exploring Pandas

In [14]:
import pandas as pd
import numpy as np

# Create DataFrame
data = {
    'Name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'Age': [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    'City': ['Nagpur', 'Mumbai', 'Delhi', 'Pune', 'Chennai',
             'Kolkata', 'Hyderabad', 'Jaipur', 'Lucknow', 'Bhopal'],
    'Salary': [30000, 40000, None, 50000, 60000,
               None, 70000, 80000, 90000, 100000]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

# info
print("\nInfo:")
df.info()

# describe
print("\nDescribe:\n", df.describe())

# Select columns
print("\nSelected Columns:\n", df[['Name', 'City']])

# Drop 'City'
df = df.drop('City', axis=1)
print("\nAfter Dropping City:\n", df)

# Fill missing Salary with mean
df['Salary'].fillna(df['Salary'].mean(), inplace=True)

# Remove duplicates
df = df.drop_duplicates()

print("\nFinal DataFrame:\n", df)

Original DataFrame:
   Name  Age       City    Salary
0    A   21     Nagpur   30000.0
1    B   22     Mumbai   40000.0
2    C   23      Delhi       NaN
3    D   24       Pune   50000.0
4    E   25    Chennai   60000.0
5    F   26    Kolkata       NaN
6    G   27  Hyderabad   70000.0
7    H   28     Jaipur   80000.0
8    I   29    Lucknow   90000.0
9    J   30     Bhopal  100000.0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

Describe:
             Age         Salary
count  10.00000       8.000000
mean   25.50000   65000.000000
std     3.02765   24494.897428
min    21.00000   30000.000000
25%    23.25000   47500.000000
50%    25.50000   650

C:\Users\DELL\AppData\Local\Temp\ipykernel_4812\3659858943.py:33: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)
